title: Match Safe Scholar
description: A website maintained by Neil Shapiro to study, evaluate, appraise, and enjoy match safes, vestas, and match holders.
email: nshapir1@nycap.rr.com
phone: (518) 436-9522

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:basename

theme: null

collections:
  sales:
    output: true

defaults:
  - scope:
      path: ""
      type: "sales"
    values:
      layout: "saleitem"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
